src/app/App.js, src/app/commons/FakeLink.js, src/app/commons/ItemListPage/ItemListPage.css, src/app/commons/ItemListPage/ItemListPage.js, src/app/exam/CreateExamModal.js, src/app/exam/ExamList.css, src/app/exam/ExamList.js, src/app/students/GroupList.js, src/app/students/StudentList.js, src/models/Group.js, src/services/StudentService.js
Complete #19  and #20 both
with the help of extracting common UI into a big component `ItemListPage`.
=> Finish StudentList and GroupList

public/index.css, src/app/App.js, src/app/admins/AdminList.js, src/app/admins/CreateAdminAccountModal.css, src/app/admins/CreateAdminAccountModal.js, src/app/commons/ItemListPage/ItemListPage.js, src/app/commons/modals/ModalHeader.css, src/app/commons/modals/ModalHeader.js, src/app/commons/modals/ModalInput.css, src/app/commons/modals/ModalInput.js, src/app/commons/modals/modal.js, src/app/commons/titles/ModalHeader.css, src/app/commons/titles/ModalHeader.js, src/app/commons/titles/TitleLine.css, src/app/commons/titles/TitleLine.js, src/app/exam/CreateExamModal.js, src/app/exam/CreateExamModel.css, src/app/exam/ExamList.css, src/app/exam/ExamList.js, src/app/students/CreateGroupModal.css, src/app/students/CreateGroupModal.js, src/app/students/CreateStudentAccountModal.css, src/app/students/CreateStudentAccountModal.js, src/app/students/GroupList.js, src/app/students/StudentList.js, src/models/Student.js, src/services/StudentService.js
Complete #24 
1. Extract components: ModalHeader, ModalInput
2. Improve css styling between ExamList and GroupList 
3. Extract a rendering method: renderModal for the modal that has a close button at the right-top corner
=> Dev/24: Create Group/Student/Admin Modal

src/app/App.js, src/app/NavigationBar.css, src/app/NavigationBar.js
=> Navigation Bar

src/services/StudentService.js
update /api/groups/{groupId}/students to /api/groups/{groupId}/members
=> update /api/groups/{groupId}/students to /api/groups/{groupId}/members

src/app/commons/ItemListPage/ItemListPage.js, src/app/exam/ExamProblems.js, src/app/exam/ExamProblems.scss, src/app/exam/modals/AddProblemModal.js, src/app/exam/modals/AddProblemModal.scss, src/models/Exam.js, src/models/Question.js, src/services/ExamService.js
=> dev/54: Exam Problem Page

src/app/exam/ExamProblems.js, src/app/exam/modals/AddProblemModal.js, src/app/exam/modals/EditProblemModal.js, src/app/exam/modals/EditProblemModal.scss, src/services/ExamService.js
The modal:
and the original value will be filled in automatically.
Since we have problem title in api's result, we can show them:
=> dev/63: Add edit problem modal

.idea/.gitignore
=> Un-track all files in .idea/ folder.

src/app/exam/ExamList.js, src/app/exam/options/ExamName.js, src/app/exam/options/ExamOptions.js
=> Dev/91 Fix all bugs about ExamOptions

src/app/App.css, src/app/App.js, src/app/admins/AdminList.js, src/app/commons/IndexBanner/InPageNavigationBar.js, src/app/commons/ItemListPage/ItemListPage.js, src/app/commons/UX/ScrollToTop.js, src/app/commons/buttons/CreateButton.js, src/app/commons/constants/Times.js, src/app/commons/modals/ModalInput.js, src/app/commons/modals/modal.js, src/app/exam/ExamInPageNavigationBar.js, src/app/exam/ExamList.js, src/app/exam/modals/AddQuestionModal.js, src/app/exam/modals/CreateExamModal.js, src/app/exam/options/ExamOptions.js, src/app/exam/participants/Examinees.js, src/app/exam/problems/ExamQuestions.js, src/app/exam/score/ExamScore.js, src/app/problem/Modal/CreateProblemModal.js, src/app/problem/ProblemEditor.js, src/app/problem/edit/ProblemEditorTitle.scss, src/app/problem/edit/Visible.js, src/app/problem/edit/testCase/TestCase.css, src/app/problem/edit/testCase/TestCases.js, src/app/problem/list/ProblemList.js, src/app/students/StudentList.js
When creating a new problem with a title,  then a new item with an empty problem name is shown
Expected: the new item should show the problem's title 
Addition: 
1. also, should go to the edit page after create  a new problem **successfully**
2. should go to the exam page after create a new exam **successfully**
------------
There is no warnings on the browser console :).
=> Dev/93 When create a new problem with title, then a new item with empty problem name is shown.

src/app/commons/ScheduleItem.js, src/app/exam/options/ExamOptions.js, src/app/exam/options/ExamSchedule.js
=> Update exam content with illegal schedule time, show warning msg

src/app/problem/ProblemEditor.js, src/app/problem/ProblemNotFound.js, src/app/problem/list/ProblemContext.js, src/app/problem/list/ProblemList.js
=> Dev/121 Problem not found page

src/app/App.css, src/app/Login.js, src/app/commons/MarkdownEditor.js, src/app/commons/TextInputForm/TextInputForm.js, src/app/commons/titles/TitleLine.js, src/app/exam/questions/ExamQuestions.js, src/app/problem/ProblemEditor.js, src/app/problem/edit/CompilationScript.js, src/app/problem/edit/TagList.js, src/app/problem/edit/TextInputItems.css
<p>
</p>
<p>
</p>
Fixed width:
=> [dev/87] Fix bug-issues as soon as possible

src/app/commons/MarkdownEditor.js, src/app/exam/questions/ExamDescriptionEditor.js, src/app/exam/questions/ExamQuestions.js, src/app/problem/ProblemEditor.js, src/models/Question.js
=> Integrate API: edit exam's description

src/app/homework/HomeworkList.js, src/app/homework/modals/CreateHomeworkModal.js, src/services/HomeworkService.js
=> [Integate API] [UI] Create Homework and Delete Homework

package.json, src/app/exam/options/ExamOptions.js, src/app/problem/ProblemEditor.js, src/app/problem/edit/EditorButton.js, src/app/problem/list/ProblemList.js, src/models/Problem.js, src/services/ProblemService.js
resolve : #109  
resolve : #150 
archive:
restore & delete:
=> archive and delete the problem

src/app/exam/submissions/ExamLiveSubmissions.js, src/models/Submission.js, src/services/LiveSubmissionsService.js, src/services/SubmissionService.js, src/services/services.js
resolve: #153 
**Before live submissions pushed**:
**After live submissions pushed**:
=> Query the latest 80 live submissions the first time get into the live submissions pages

src/app/exam/modals/AddQuestionModal.js, src/app/exam/modals/EditQuestionModal.js, src/models/Question.js
=> :bug: Fixed #159.

src/app/exam/ExamList.js, src/app/exam/options/ExamOptions.js, src/services/ExamService.js
=> Dev/115 Delete Exam Modal

src/app/exam/model.js
Resolved the bug caused by ES6 class syntax.
=> Remove the class private method syntax.

src/app/problem-old/ProblemEditorOld.js, src/app/problem-old/edit/ProblemEditorTitle.js, src/app/problem/editor/right/Description.js, src/app/problem/editor/right/ProblemTitle.js, src/app/problem/editor/right/Visible.js, src/services/ProblemService.js
=> Dev/180 New Problem Editor: Visible / New Problem Editor: Description. 

package.json, src/app/commons/ScheduleItem.js, src/app/exam/modals/CreateExamModal.js, src/app/exam/options/ExamSchedule.js, src/app/exam/score/ExamScorePage.js, src/app/exam/scoreboard/ChartField.js, src/app/exam/scoreboard/ExamScoreboardPage.js, src/app/exam/scoreboard/ExamScoreboardPresenter.js, src/services/ExamTranscriptService.js, src/services/services.js, src/utils/utils.js
=> Resolve #195 #154: Polling LiveScoreBoard / Allow startTime to be earlier than now

src/app/commons/modals/ModalInput.js, src/app/commons/titles/TitleLine.js, src/app/exam/ExamInPageNavigationBar.js, src/app/exam/ExamList.js, src/app/exam/ExamList.scss, src/app/exam/modals/AddQuestionModal.js, src/app/exam/options/ExamName.js, src/app/exam/options/ExamOptions.js, src/app/exam/options/ExamOptions.scss, src/app/exam/participants/Examinees.js, src/app/exam/questions/ExamDescription.js, src/app/exam/questions/ExamDescription.scss, src/app/exam/questions/ExamQuestions.js, src/app/exam/questions/ExamQuestions.scss, src/app/exam/score/ExamScorePage.js, src/app/exam/scoreboard/ExamScoreboardPage.js, src/app/exam/submissions/ExamLiveSubmissions.js, src/app/problem/ProblemList.js, src/app/problem/ProblemList.scss, src/app/problem/editor/ProblemEditor.js, src/app/problem/editor/ProblemEditor.scss, src/app/problem/editor/right/Block.js, src/app/problem/editor/right/Description.js, src/app/problem/editor/right/ProblemDescription.js, src/app/problem/editor/right/ProblemTitle.js, src/app/problem/editor/right/RightBar.js, src/app/problem/editor/right/Visible.js, src/services/ExamService.js
Under construction. Don't review for now.
=> Dev/186 New Markdown Editor: Bugs in ExamQuestions.

src/app/homework/HomeworkList.js, src/app/homework/HomeworkPageNavigationBar.js, src/app/homework/progress/HomeworkContext.js, src/app/homework/progress/HomeworkPage.scss, src/app/homework/progress/HomeworkProgressPage.js
=> [UI] Homework page #140

src/app/problem/ProblemList.js, src/app/problem/ProblemList.scss, src/app/problem/editor/right/Tags.js, src/services/ProblemService.js
=> Dev/207 Tags API integrate

src/app/problem/editor/left/LeftBar.js, src/app/problem/editor/right/testcases/TestcaseEditor.js, src/app/problem/editor/right/testcases/TestcaseEditor.scss, src/app/problem/editor/right/testcases/Testcases.js, src/app/problem/editor/right/testcases/usecase.js, src/services/ProblemService.js, src/utils/array.js
[API Integration] Testcase Upsertion
resolve: #201
=> dev/201: [API Integration] Testcase Upsertion

src/app/problem/Model.js, src/app/problem/editor/right/CompilationScript.js, src/app/problem/editor/right/CompilationScript.scss
=> Dev/177 Compilation script API integrate

src/app/problem/Model.js, src/app/problem/editor/right/ResourceSpec.js
=> Dev/176: New Problem Editor: Resource Spec. #176

src/app/students/StudentList.js, src/services/StudentService.js
=> Dev/164 Delete student modal

src/app/commons/modals/DeleteConfirmationModal.js, src/app/commons/modals/DeleteConfirmationModal.scss, src/app/problem/editor/ProblemEditor.scss, src/app/problem/editor/right/ActionItem.scss, src/app/problem/editor/right/Actions.js, src/app/problem/editor/right/Visible.js
=> Dev/179 Actions in the New Problem Editor

package.json, public/index.css, src/app/commons/buttons/CreateButton.js, src/app/problem/ProblemList.js, src/app/problem/ProblemList.scss, src/services/ProblemService.js
resolve: #189 
**Visible Problems**
---
**Invisible Problems**
---
**Archive Problems**
=> Dev/189 [UI] New Problem List

src/app/exam/questions/ExamQuestions.js, src/app/exam/questions/ExamQuestions.scss, src/app/exam/submissions/ExamLiveSubmissions.js
**before fix:**
---
**after fix:**
**before adding:**
**after adding:**
=> Dev/130 [ExamQuestion] Question order jumping number

package.json, src/app/problem/commons/EditSaveCancelButton.js, src/app/problem/commons/EditorButton.js, src/app/problem/editor/right/testcases/TestcaseEditor.js, src/app/problem/editor/right/testcases/TestcaseEditor.scss, src/app/problem/editor/right/testcases/Testcases.js, src/app/problem/editor/right/testcases/usecase.js, src/services/ProblemService.js
=> :sparkles: dev/211 TestcaseEditor Validation and Refactoring

src/app/exam/modals/CreateExamModal.js, src/app/exam/options/ExamOptions.js, src/app/exam/options/ExamSchedule.js
=> Exam Schedule time-zone inconsistency #218

.eslintrc.json, src/app/commons/ItemListPage/ItemListPage.js, src/app/exam/modals/CreateExamModal.js, src/app/exam/questions/ExamQuestions.js, src/app/problem/commons/EditSaveCancelButton.js, src/app/problem/editor/SectionNavigationBar.js, src/app/problem/editor/sections/CompilationScriptSection.js, src/app/problem/editor/sections/VisibilitySection.js, src/services/ExamService.js
resolve: #221 
https://user-images.githubusercontent.com/26381900/136546465-f76af49b-9ffa-408a-aae7-408892179529.mov
=> Dev/221 [ExamQuestion] Change exam questions by mouse scrolling

src/app/Login.js, src/services/StudentService.js
=> Dev/219 Logout the account automatically when the token expired #219

src/app/problem/editor/sections/testcases/TestcaseEditor.js
=> Dev/238 Solved Testcase IO Bug

src/app/exam/questions/ExamContext.js, src/app/problem/ProblemList.js, src/app/problem/editor/ProblemEditorRoot.js, src/app/problem/editor/context.js, src/app/problem/editor/sections/ActionsSection.js, src/app/problem/editor/sections/ProblemTitleSection.js, src/app/problem/editor/sections/TagsSection.js, src/app/problem/editor/sections/VisibilitySection.js, src/services/LiveSubmissionsService.js, src/services/StompClient.js
=> Dev/230 ProblemList should be updated when any problem's title, tags is updated or some actions apply to it

src/app/exam/options/ExamOptions.js, src/app/exam/options/ExamWhiteList.js, src/app/problem/editor/sections/testcases/TestcaseEditor.js, src/models/Exam.js
resolve: #232 
https://user-images.githubusercontent.com/26381900/140686743-ad666592-071c-463a-b2a1-3a4c6d0a7102.mov
=> Dev/232 The ExamWhiteList component can't be rendered in the ExamOption component
